version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk

    working_directory: ~/test

    steps:
    - checkout
    - run: gradle dependencies
    - run: gradle build
    - run: gradle test