version: 2
jobs:
  build:
    docker:
    - image: gradle:alpine

    working_directory: ~/test

    steps:
    - checkout
    - run: gradle dependencies
    - run: gradle build
    - run: gradle test